### ISSUE TITLE
\sum has been redefined but needs tweaking

### ISSUE THREAD

**Issue by andrew-edwards** [andrew-edwards/csas-latex#5]
So in the header for Redbanded and Yelloweye .tex assessments (not give here), I redefined 

\usepackage{relsize}
\renewcommand{\sum}{{\mathlarger{\mathlarger{\mathlarger{\mathlarger{\mathlarger{\Sigma}}}}}}}
                                        % Crude fix to \sum encoding issues. Get:
                                        % LaTeX Font Warning: Size substitutions 
                                        %   with differences (Font) up to 
                                        %   1.6414pt have occurred.
                                        %  Use \Sigma in inline mode $\Sigma $

because the web accessibility check on the .pdf gives encoding errors. I presume this is because it is encoded as \sum not as \Sigma, doing the renewcommand above fixes this. However, the \Sigma is not centered around the centerline for fractions, so it doesn't look as good as the default \sum (i.e. \sum does it sensibly).
Also, with \sum_{i=1}^n  you now get subscripts and superscripts (after the Sigma), rather than below and above like you properly get with the default. Again, Latex knows what it's doing. 
I didn't fix this for current assessments but it would be good.  Maybe it involves delving into the original \sum definition, rather than my crude \Sigma fix.

**Comment by andrew-edwards** [comment]
Or find a better way to keep \sum, such as to do with the encoding. Only other issues I've had are with large ( and ) around equations (and one unidentified one), but that's allowable.
Also should check the default \sum without _{i=1}^n  in case the issue is with the annotation above and below, rather than with the \sum not \sigma (I don't think it is, but worth a quick test).

**Comment by cgrandin** [comment]
If you put this code chunk in the _resDocSty.sty_ file it should take care of the problem without
the need to replace all the _\sum_ commands in your latex files. The _scalerel_ package makes it so the Sigma fits the rest of the equation properly (correct size).

%% The \sum command creates encoding errors in the final PDF so it is replaced
%%  globally here with Sigma. The * in DeclareMathOperator* makes the limits
%%  appear above and below the Sigma symbol instead of in front of it.
%% This declaration means you can just use \sum in the latex code and the errors
%%  for character encoding will not occur.
\usepackage{scalerel}
\let\oldsum\sum
\DeclareMathOperator*{\summ}{\scalerel*{\Sigma}{\oldsum}}
\renewcommand{\sum}{\summ}

**Comment by cgrandin** [comment]
This has been fixed and is included in the mwe branch: https://github.com/cgrandin/csas-latex/tree/mwe

**Comment by andrew-edwards** [comment]
Yes, is now in https://github.com/cgrandin/csas-style/blob/master/res-doc.sty
